version: 2

multi-ecosystem-groups:
  android-maintenance:
    schedule:
      interval: monthly

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - '*'
    multi-ecosystem-group: android-maintenance
    open-pull-requests-limit: 1
    cooldown:
      default-days: 30

  - package-ecosystem: gradle
    directory: /
    patterns:
      - '*'
    multi-ecosystem-group: android-maintenance
    open-pull-requests-limit: 1
    cooldown:
      default-days: 30
      semver-major-days: 60
