version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    groups:
      actions-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    groups:
      gradle-dev-patch-minor:
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - patch
          - minor
        exclude-patterns:
          - 'com.android.*'
          - 'org.jetbrains.kotlin.*'
          - 'com.google.devtools.ksp'
          - 'com.google.dagger.*'
          - 'androidx.room.*'
          - 'com.google.gms.*'
          - 'com.google.firebase.*'
          - 'com.github.triplet.play'
          - 'com.android.billingclient.*'
      gradle-prod-patch-minor:
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - patch
          - minor
        exclude-patterns:
          - 'com.android.*'
          - 'org.jetbrains.kotlin.*'
          - 'com.google.devtools.ksp'
          - 'com.google.dagger.*'
          - 'androidx.room.*'
          - 'com.google.gms.*'
          - 'com.google.firebase.*'
          - 'com.github.triplet.play'
          - 'com.android.billingclient.*'

  - package-ecosystem: pip
    directory: /scripts/ci
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
    groups:
      pip-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/admin-notifications
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/cloudflare/workers/admin-api
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/cloudflare/workers/content-api
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/cloudflare/workers/ssv-callback
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/firebase/functions
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /side-projects/firebase/rules-tests
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 2
    rebase-strategy: disabled
    groups:
      npm-patch-minor:
        patterns:
          - '*'
        update-types:
          - patch
          - minor
