title = "Android multi-app framework secret scanning"

[extend]
useDefault = true

[allowlist]
description = "Ignore public Cloudflare Access AUD ID"
regexes = [
  '''5069a4e84e68eb9898e8831ce46e9d93a5c26a3892f19bde0f37e57a94948287'''
]
