#!/usr/bin/env python3
"""
Unit tests for scripts/ci/classify_pr.py
"""

from __future__ import annotations

import os
import sys
import unittest
from unittest.mock import MagicMock, patch

sys.path.insert(0, os.path.dirname(__file__))
from classify_pr import (
    fetch_all_pr_files,
    fetch_pr_provenance,
    is_verified_fleet_pr,
    update_pr_labels,
    main,
)


class TestClassifyPR(unittest.TestCase):
    @patch("classify_pr._make_request")
    def test_pagination_fetches_multiple_pages(self, mock_req: MagicMock):
        # Page 1 has 100 files, Page 2 has 25 files
        page1 = [{"filename": f"app/src/File{i}.kt"} for i in range(100)]
        page2 = [{"filename": f"app/src/File{i}.kt"} for i in range(100, 125)]

        mock_req.side_effect = [
            (200, page1),
            (200, page2),
        ]

        files = fetch_all_pr_files("owner/repo", 123, "fake-token")
        self.assertEqual(len(files), 125)
        self.assertEqual(mock_req.call_count, 2)

    @patch("classify_pr._make_request")
    def test_fetch_pr_provenance_uses_graphql(self, mock_req: MagicMock):
        payload = {
            "data": {
                "repository": {
                    "pullRequest": {
                        "headRefName": "jules/fix-42/s-abc123",
                        "headRepository": {"nameWithOwner": "owner/repo"},
                        "body": "Fixes #42",
                        "closingIssuesReferences": {
                            "nodes": [
                                {
                                    "number": 42,
                                    "labels": {"nodes": [{"name": "fleet"}]},
                                }
                            ]
                        },
                    }
                }
            }
        }
        mock_req.return_value = (200, payload)
        provenance = fetch_pr_provenance("owner/repo", 123, "fake-token")
        self.assertEqual(provenance["headRefName"], "jules/fix-42/s-abc123")
        call = mock_req.call_args
        self.assertEqual(call[0][0], "https://api.github.com/graphql")
        self.assertEqual(call[1]["method"], "POST")
        self.assertEqual(call[1]["data"]["variables"]["number"], 123)

    def test_verified_fleet_pr_requires_correlated_provenance_and_fleet_issue(self):
        good = {
            "headRefName": "fix-42-live-canary-14900125275473977334",
            "headRepository": {"nameWithOwner": "owner/repo"},
            "body": (
                "Fixes #42\n"
                "Auto-generated by Jules: "
                "https://jules.google.com/task/14900125275473977334"
            ),
            "closingIssuesReferences": {
                "nodes": [
                    {"number": 42, "labels": {"nodes": [{"name": "fleet"}]}}
                ]
            },
        }
        self.assertTrue(is_verified_fleet_pr("owner/repo", good))

        legacy = {
            **good,
            "headRefName": "jules/fix-42/s-abc123",
            "body": (
                "Fixes #42\n"
                "Session: https://jules.google.com/session/s-abc123"
            ),
        }
        self.assertTrue(is_verified_fleet_pr("owner/repo", legacy))

        forked = {**good, "headRepository": {"nameWithOwner": "fork/repo"}}
        self.assertFalse(is_verified_fleet_pr("owner/repo", forked))

        mismatched_body = {
            **good,
            "body": (
                "Fixes #42\n"
                "https://jules.google.com/task/99999999999999999999"
            ),
        }
        self.assertFalse(is_verified_fleet_pr("owner/repo", mismatched_body))

        no_body_marker = {**good, "body": "Fixes #42"}
        self.assertFalse(is_verified_fleet_pr("owner/repo", no_body_marker))

        no_numeric_suffix = {
            **good,
            "headRefName": "fix-42-live-canary",
        }
        self.assertFalse(is_verified_fleet_pr("owner/repo", no_numeric_suffix))

        no_fleet_issue = {
            **good,
            "closingIssuesReferences": {
                "nodes": [
                    {"number": 42, "labels": {"nodes": [{"name": "bug"}]}}
                ]
            },
        }
        self.assertFalse(is_verified_fleet_pr("owner/repo", no_fleet_issue))

    @patch("classify_pr.update_pr_labels")
    @patch("classify_pr.fetch_all_pr_files")
    @patch("classify_pr.is_verified_fleet_pr")
    @patch("classify_pr.fetch_pr_provenance")
    def test_main_non_fleet_exits_before_file_classification_or_label_writes(
        self,
        mock_provenance: MagicMock,
        mock_verified: MagicMock,
        mock_files: MagicMock,
        mock_update: MagicMock,
    ):
        mock_provenance.return_value = {"headRefName": "feature/human"}
        mock_verified.return_value = False
        with patch.dict(
            os.environ,
            {
                "GITHUB_REPOSITORY": "owner/repo",
                "PR_NUMBER": "123",
                "GITHUB_TOKEN": "token",
            },
            clear=True,
        ):
            self.assertEqual(main(), 0)
        mock_files.assert_not_called()
        mock_update.assert_not_called()

    @patch("classify_pr._make_request")
    def test_low_risk_non_fleet_removes_fleet_ready(self, mock_req: MagicMock):
        mock_req.return_value = (200, {})
        update_pr_labels(
            "owner/repo",
            123,
            "fake-token",
            "LOW_RISK",
            fleet_verified=False,
        )
        added = [
            call[1]["data"]["labels"][0]
            for call in mock_req.call_args_list
            if call[1].get("method") == "POST"
        ]
        deleted_urls = [
            call[0][0]
            for call in mock_req.call_args_list
            if call[1].get("method") == "DELETE"
        ]
        self.assertEqual(added, ["risk:low"])
        self.assertTrue(any("fleet-merge-ready" in url for url in deleted_urls))

    @patch("classify_pr._make_request")
    def test_update_labels_low_risk(self, mock_req: MagicMock):
        mock_req.side_effect = [
            (200, {}),  # add fleet-merge-ready
            (200, {}),  # add risk:low
            (200, {}),  # del fleet-review-required
            (200, {}),  # del risk:protected
        ]
        update_pr_labels("owner/repo", 123, "fake-token", "LOW_RISK", fleet_verified=True)
        self.assertEqual(mock_req.call_count, 4)

        add_call = mock_req.call_args_list[0]
        self.assertIn("issues/123/labels", add_call[0][0])
        self.assertEqual(add_call[1]["data"], {"labels": ["fleet-merge-ready"]})

        add_call = mock_req.call_args_list[1]
        self.assertEqual(add_call[1]["data"], {"labels": ["risk:low"]})

    @patch("classify_pr._make_request")
    def test_update_labels_protected(self, mock_req: MagicMock):
        mock_req.side_effect = [
            (200, {}),  # add fleet-review-required
            (200, {}),  # add risk:protected
            (200, {}),  # del fleet-merge-ready
            (200, {}),  # del risk:low
        ]
        update_pr_labels("owner/repo", 123, "fake-token", "PROTECTED", fleet_verified=True)
        self.assertEqual(mock_req.call_count, 4)

        add_call = mock_req.call_args_list[0]
        self.assertIn("issues/123/labels", add_call[0][0])
        self.assertEqual(add_call[1]["data"], {"labels": ["fleet-review-required"]})

        add_call = mock_req.call_args_list[1]
        self.assertEqual(add_call[1]["data"], {"labels": ["risk:protected"]})

    @patch("classify_pr._make_request")
    def test_update_labels_add_failure_raises(self, mock_req: MagicMock):
        mock_req.return_value = (
            403,
            {"message": "Resource not accessible by integration"},
        )
        with self.assertRaises(RuntimeError) as ctx:
            update_pr_labels("owner/repo", 123, "fake-token", "LOW_RISK", fleet_verified=True)
        self.assertIn("Failed to add label", str(ctx.exception))

    @patch("classify_pr._make_request")
    def test_update_labels_remove_404_ignored(self, mock_req: MagicMock):
        # add fleet-merge-ready, add risk:low, del fleet-review-required (404), del risk:protected (404)
        mock_req.side_effect = [
            (200, {}),  # add fleet-merge-ready
            (200, {}),  # add risk:low
            (404, {"message": "Label does not exist"}),  # del fleet-review-required
            (404, {"message": "Label does not exist"}),  # del risk:protected
        ]
        # Should NOT raise
        update_pr_labels("owner/repo", 123, "fake-token", "LOW_RISK", fleet_verified=True)
        self.assertEqual(mock_req.call_count, 4)

    @patch("classify_pr._make_request")
    def test_update_labels_remove_other_error_raises(self, mock_req: MagicMock):
        # add fleet-merge-ready, add risk:low, del fleet-review-required (200), del risk:protected (500)
        mock_req.side_effect = [
            (200, {}),  # add fleet-merge-ready
            (200, {}),  # add risk:low
            (200, {}),  # del fleet-review-required
            (500, {"message": "Internal Server Error"}),  # del risk:protected
        ]
        with self.assertRaises(RuntimeError) as ctx:
            update_pr_labels("owner/repo", 123, "fake-token", "LOW_RISK", fleet_verified=True)
        self.assertIn("Failed to remove label 'fleet-review-required'", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
