#!/usr/bin/env python3
"""Render deterministic dependency catalog audit reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


def append_entry_table(lines: List[str], title: str, entries: List[Dict[str, Any]], identifier: str) -> None:
    lines.extend(["", f"## {title}", "", f"| Alias | {identifier} | Version | Source |", "|---|---|---:|---|"])
    id_key = "coordinate" if title == "Libraries" else "id"
    fallback = "BOM/platform" if title == "Libraries" else "managed"
    for entry in entries:
        version = entry["version"] if entry["version"] is not None else fallback
        lines.append(
            f"| `{entry['alias']}` | `{entry[id_key]}` | `{version}` | `{entry['versionSource']}` |"
        )


def append_list(lines: List[str], title: str, values: List[str]) -> None:
    lines.extend(["", f"## {title}", ""])
    lines.extend(f"- `{value}`" for value in values)
    if not values:
        lines.append("- None")


def markdown_report(inventory: Dict[str, Any]) -> str:
    summary = inventory["summary"]
    lines = [
        "# Dependency Catalog Audit",
        "",
        "This report is generated by `scripts/ci/audit_dependency_catalog.py`.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    labels = [
        ("Version keys", "versionKeys"),
        ("Library aliases", "libraries"),
        ("Plugin aliases", "plugins"),
        ("Inline versions", "inlineVersions"),
        ("Catalog prereleases", "catalogPrereleases"),
        ("Unused version keys", "unusedVersionKeys"),
        ("Transitive prerelease allowlist", "transitivePrereleaseAllowlist"),
    ]
    lines.extend(f"| {label} | {summary[key]} |" for label, key in labels)
    append_entry_table(lines, "Libraries", inventory["libraries"], "Coordinate")
    append_entry_table(lines, "Plugins", inventory["plugins"], "Plugin ID")
    append_list(lines, "Transitive prerelease allowlist", inventory["transitivePrereleaseAllowlist"])
    append_list(lines, "Unused version keys", inventory["unusedVersionKeys"])
    return "\n".join(lines) + "\n"


def write_reports(inventory: Dict[str, Any], json_path: Path, markdown_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path.write_text(markdown_report(inventory), encoding="utf-8")
