#!/usr/bin/env python3
"""Pure helpers for Gradle/D8/ASM warning regression auditing."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from gradle_warning_policy import load_policy, validate_policy

ASM_WARNING = "ASM Instrumentation process wasn't able to resolve some classes"


def warning_category(line: str) -> Optional[str]:
    if " has been deprecated." in line or " method has been deprecated." in line:
        return "gradle-deprecation"
    if "D8:" in line:
        return "d8"
    if ASM_WARNING in line:
        return "asm-unresolved-classes"
    return None


def normalize_line(line: str) -> str:
    return " ".join(line.strip().split())


def extract_asm_details(lines: Sequence[str], start_index: int) -> List[str]:
    details: List[str] = []
    for line in lines[start_index + 1 :]:
        stripped = line.strip()
        if stripped.startswith("> "):
            details.append(stripped[2:])
        elif stripped.startswith("-- ") and stripped.endswith(" more classes --"):
            details.append(stripped)
        elif details:
            break
    return details


def extract_warnings(text: str) -> List[Dict[str, Any]]:
    lines = text.splitlines()
    warnings: List[Dict[str, Any]] = []
    seen: set[Tuple[str, str]] = set()
    for index, line in enumerate(lines):
        category = warning_category(line)
        if category is None:
            continue
        normalized = normalize_line(line)
        key = (category, normalized)
        if key in seen:
            continue
        seen.add(key)
        details = extract_asm_details(lines, index) if category == "asm-unresolved-classes" else []
        warnings.append(
            {
                "category": category,
                "line": normalized,
                "lineNumber": index + 1,
                "details": details,
            }
        )
    return warnings



def match_warnings(
    warnings: Sequence[Dict[str, Any]],
    policy_entries: Sequence[Dict[str, str]],
) -> Tuple[List[Dict[str, Any]], List[str]]:
    errors: List[str] = []
    observed: List[Dict[str, Any]] = []
    for warning in warnings:
        matches = [
            entry
            for entry in policy_entries
            if entry["category"] == warning["category"] and entry["match"] in warning["line"]
        ]
        if not matches:
            errors.append(
                f"Unapproved {warning['category']} warning on line {warning['lineNumber']}: {warning['line']}"
            )
            observed.append({**warning, "policyId": None})
            continue
        if len(matches) > 1:
            errors.append(
                f"Warning matches multiple policy entries on line {warning['lineNumber']}: {warning['line']}"
            )
        observed.append({**warning, "policyId": matches[0]["id"]})
    return observed, errors


def build_report(
    log_path: Path,
    observed: Sequence[Dict[str, Any]],
    policy_entries: Sequence[Dict[str, str]],
) -> Dict[str, Any]:
    categories: Dict[str, int] = {}
    for warning in observed:
        category = str(warning["category"])
        categories[category] = categories.get(category, 0) + 1
    return {
        "log": str(log_path),
        "summary": {
            "observedWarnings": len(observed),
            "policyEntries": len(policy_entries),
            "observedByCategory": dict(sorted(categories.items())),
        },
        "observedWarnings": list(observed),
        "policyEntries": list(policy_entries),
    }


def markdown_report(report: Dict[str, Any]) -> str:
    summary = report["summary"]
    lines = [
        "# Gradle Warning Audit",
        "",
        "This report is generated by `scripts/ci/validate_gradle_warning_report.py`.",
        "",
        f"- Observed warnings: **{summary['observedWarnings']}**",
        f"- Policy entries: **{summary['policyEntries']}**",
        "",
        "## Observed warnings",
        "",
        "| Category | Policy | Line | Details |",
        "|---|---|---:|---|",
    ]
    for warning in report["observedWarnings"]:
        details = ", ".join(warning.get("details", [])) or "—"
        policy_id = warning.get("policyId") or "UNAPPROVED"
        lines.append(
            f"| `{warning['category']}` | `{policy_id}` | {warning['lineNumber']} | {details} |"
        )
    if not report["observedWarnings"]:
        lines.append("| — | — | — | No tracked warnings observed |")
    lines.extend(
        [
            "",
            "## Policy entries",
            "",
            "| ID | Category | Owner | Source | Expires |",
            "|---|---|---|---|---:|",
        ]
    )
    for entry in report["policyEntries"]:
        lines.append(
            f"| `{entry['id']}` | `{entry['category']}` | `{entry['owner']}` | "
            f"`{entry['source']}` | `{entry['expires_on']}` |"
        )
    return "\n".join(lines) + "\n"


def write_reports(report: Dict[str, Any], json_path: Path, markdown_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path.write_text(markdown_report(report), encoding="utf-8")
