#!/usr/bin/env python3
"""Unit tests for scripts/ci/jules_provenance.py."""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(__file__))

from jules_provenance import (
    extract_verified_jules_session_id,
    has_verified_jules_session_provenance,
)


class TestJulesProvenance(unittest.TestCase):
    def test_current_numeric_runtime_provenance_must_correlate(self):
        head = "fix-171-live-canary-verification-3904992159357426987"
        body = (
            "Fixes #171\n"
            "Auto-generated by Jules: "
            "https://jules.google.com/task/3904992159357426987"
        )
        self.assertEqual(
            extract_verified_jules_session_id(head, body),
            "3904992159357426987",
        )
        self.assertTrue(has_verified_jules_session_provenance(head, body))

    def test_current_runtime_rejects_mismatched_or_missing_markers(self):
        head = "fix-171-live-canary-verification-3904992159357426987"
        self.assertFalse(
            has_verified_jules_session_provenance(
                head,
                "https://jules.google.com/task/99999999999999999999",
            )
        )
        self.assertFalse(
            has_verified_jules_session_provenance(head, "Fixes #171")
        )
        self.assertFalse(
            has_verified_jules_session_provenance(
                "fix-171-live-canary-verification",
                "https://jules.google.com/task/3904992159357426987",
            )
        )

    def test_current_runtime_accepts_session_url_with_same_id(self):
        head = "fix-171-live-canary-verification-3904992159357426987"
        body = "https://jules.google.com/session/3904992159357426987"
        self.assertTrue(has_verified_jules_session_provenance(head, body))

    def test_legacy_s_session_requires_jules_branch_and_matching_body(self):
        head = "jules/fix-42/s-abc123"
        body = "Session: https://jules.google.com/session/s-abc123"
        self.assertEqual(
            extract_verified_jules_session_id(head, body),
            "s-abc123",
        )
        self.assertFalse(
            has_verified_jules_session_provenance(
                "feature/fix-42-s-abc123",
                body,
            )
        )
        self.assertFalse(
            has_verified_jules_session_provenance(
                head,
                "Session: https://jules.google.com/session/s-other",
            )
        )


if __name__ == "__main__":
    unittest.main()
