"""Render/Generate derived repository maintenance surfaces from canonical autonomy policy."""

import os
from typing import Any, Dict, List
import yaml
from maintenance.policy import AutonomyPolicy

def generate_dependabot_yml(policy: AutonomyPolicy) -> str:
    """Generates canonical .github/dependabot.yml content from AutonomyPolicy."""
    updates = []

    # 1. GitHub Actions
    updates.append({
        "package-ecosystem": "github-actions",
        "directory": "/",
        "schedule": {"interval": "weekly", "day": "sunday"},
        "open-pull-requests-limit": 3,
        "groups": {
            "actions-patch-minor": {
                "patterns": ["*"],
                "update-types": ["patch", "minor"]
            }
        }
    })

    # 2. Gradle
    gradle_excludes = policy.protected_gradle_patterns
    updates.append({
        "package-ecosystem": "gradle",
        "directory": "/",
        "schedule": {"interval": "weekly", "day": "sunday"},
        "open-pull-requests-limit": 3,
        "groups": {
            "gradle-dev-patch-minor": {
                "dependency-type": "development",
                "patterns": ["*"],
                "update-types": ["patch", "minor"],
                "exclude-patterns": gradle_excludes
            },
            "gradle-prod-patch": {
                "dependency-type": "production",
                "patterns": ["*"],
                "update-types": ["patch"],
                "exclude-patterns": gradle_excludes
            }
        }
    })

    # 3. Pip (CI)
    updates.append({
        "package-ecosystem": "pip",
        "directory": "/scripts/ci",
        "schedule": {"interval": "weekly", "day": "sunday"},
        "open-pull-requests-limit": 3,
        "groups": {
            "pip-patch-minor": {
                "patterns": ["*"],
                "update-types": ["patch", "minor"]
            }
        }
    })

    # 4. NPM Directories
    npm_excludes = policy.protected_npm_patterns
    for npm_dir in policy.dependabot_directories:
        updates.append({
            "package-ecosystem": "npm",
            "directory": npm_dir,
            "schedule": {"interval": "weekly", "day": "sunday"},
            "open-pull-requests-limit": 3,
            "groups": {
                "npm-dev-patch-minor": {
                    "dependency-type": "development",
                    "patterns": ["*"],
                    "update-types": ["patch", "minor"],
                    "exclude-patterns": npm_excludes
                },
                "npm-prod-patch": {
                    "dependency-type": "production",
                    "patterns": ["*"],
                    "update-types": ["patch"],
                    "exclude-patterns": npm_excludes
                }
            }
        })

    data = {
        "version": 2,
        "updates": updates
    }

    content = "# Generated by python3 -m maintenance generate from config/autonomy-policy.yaml\n"
    content += "# DO NOT EDIT DIRECTLY — Run 'python3 -m maintenance generate' to update.\n"
    content += yaml.dump(data, sort_keys=False, default_flow_style=False)
    return content

def project_all_surfaces(policy_path: str = "config/autonomy-policy.yaml", write: bool = False) -> Dict[str, bool]:
    """Generates derived files and compares or writes them. Returns drift status per file."""
    policy = AutonomyPolicy.load(policy_path)
    results = {}

    target_path = ".github/dependabot.yml"
    new_content = generate_dependabot_yml(policy)

    current_content = ""
    if os.path.exists(target_path):
        with open(target_path, "r", encoding="utf-8") as f:
            current_content = f.read()

    drift = (current_content.strip() != new_content.strip())
    results[target_path] = drift

    if write and drift:
        with open(target_path, "w", encoding="utf-8") as f:
            f.write(new_content)

    return results
